version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: henhouse-webserver
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:80"
    links:
      - node
  node:
    image: node:alpine
    container_name: henhouse-node
    volumes:
      - .:/src
    ports:
      - "3001:3000"
    command: "npm start"